"""
test_executive.py — Executive Runtime (persistent task engine).

Covers the identity-runtime executive subsystem:
  1. Data model & state machine (legal/illegal transitions, progress).
  2. Persistence: tasks survive engine restart; interruption recovery.
  3. Generic capability acquisition end-to-end with per-step evidence.
  4. Marketplace-found capability skips generate/validate/publish.
  5. Queue ordering by priority, scheduler background execution.
  6. Failure / retry / force-resume / cancel / pause semantics.
  7. Evidence rules: every completed step has real evidence; no hallucination.
  8. Executive capability API for identities (start/status/resume/...).
  9. Truthful reporting: task_status/task_progress reflect persisted state.

Capabilities generated by tests use the ``exec_test_*`` prefix and are
removed after each test so the repo stays clean.
"""

import os
import re
import shutil
import sys
import time

import pytest

from core.capabilities.registry import lookup
from core.executive import ExecutiveRuntime
from core.executive.engine import get_executive_for, register_executive
from core.executive.models import TaskStatus, TaskStepStatus
from core.executive.state import IllegalTransition
from core.executive.workflow import extract_capability_name, is_acquisition_goal
from runtime.persistence import JSONFileBackend


# ── Fixtures ─────────────────────────────────────────────────────────────

_GENERATED_PREFIX = "exec_test_"


@pytest.fixture()
def storage(tmp_path):
    return JSONFileBackend(root_dir=str(tmp_path / "store"))


@pytest.fixture()
def registry(storage):
    from core.capabilities.registry import CapabilityRegistry
    return CapabilityRegistry(storage=storage)


@pytest.fixture()
def engine(storage, registry):
    eng = ExecutiveRuntime(storage=storage, capability_registry=registry)
    register_executive(eng)
    yield eng
    eng.shutdown()


def _run_until_terminal(eng, identity, task_id, cap=200):
    guard = 0
    while guard < cap:
        eng.process_ready(identity)
        t = eng.get_task(identity, task_id)
        if t.status.value in ("completed", "failed", "cancelled"):
            return t
        guard += 1
    return eng.get_task(identity, task_id)


def _cleanup_generated(cap_id):
    root = os.path.join(os.path.dirname(__file__), "..")
    for rel in (
        f"core/capabilities/{cap_id}",
        f"registry/capabilities/{cap_id}",
    ):
        p = os.path.normpath(os.path.join(root, rel))
        if os.path.isdir(p):
            shutil.rmtree(p, ignore_errors=True)
    index = os.path.normpath(os.path.join(root, "registry/capabilities/index.json"))
    if os.path.exists(index):
        import json
        with open(index) as f:
            data = json.load(f)
        caps = data.get("capabilities", [])
        data["capabilities"] = [c for c in caps if c.get("id") != cap_id]
        with open(index, "w") as f:
            json.dump(data, f, indent=2)
    root_index = os.path.normpath(os.path.join(root, "registry/index.json"))
    if os.path.exists(root_index):
        import json
        with open(root_index) as f:
            data = json.load(f)
        caps = data.get("capabilities", [])
        data["capabilities"] = [c for c in caps if c.get("id") != cap_id]
        with open(root_index, "w") as f:
            json.dump(data, f, indent=2)


@pytest.fixture()
def fresh_cap():
    """Yield a unique, marketplace-absent capability id; clean up after."""
    cap_id = f"{_GENERATED_PREFIX}{int(time.time() * 1000)}"
    yield cap_id
    _cleanup_generated(cap_id)


# ── 1. Model & state machine ─────────────────────────────────────────────

def test_task_progress_derived_from_steps():
    from core.executive.models import Task, TaskStep
    t = Task(task_id="t1", goal="g", identity_id="i")
    t.steps = [TaskStep(action=f"a{n}", description=str(n)) for n in range(4)]
    assert t.progress == 0.0
    t.steps[0].status = TaskStepStatus.COMPLETED
    t.steps[1].status = TaskStepStatus.COMPLETED
    assert t.progress == 0.5


def test_state_machine_legal_and_illegal_transitions():
    from core.executive.models import Task
    from core.executive.state import can_transition
    t = Task(task_id="t", goal="g", identity_id="i")

    assert can_transition(TaskStatus.QUEUED, TaskStatus.RUNNING)
    assert can_transition(TaskStatus.RUNNING, TaskStatus.BLOCKED)
    assert can_transition(TaskStatus.RUNNING, TaskStatus.COMPLETED)
    assert can_transition(TaskStatus.RUNNING, TaskStatus.FAILED)
    assert can_transition(TaskStatus.RUNNING, TaskStatus.CANCELLED)
    assert can_transition(TaskStatus.BLOCKED, TaskStatus.RUNNING)
    assert can_transition(TaskStatus.FAILED, TaskStatus.RUNNING)
    assert not can_transition(TaskStatus.RUNNING, TaskStatus.QUEUED)

    t.status = TaskStatus.COMPLETED
    for illegal in (TaskStatus.RUNNING, TaskStatus.BLOCKED, TaskStatus.FAILED, TaskStatus.QUEUED, TaskStatus.CANCELLED):
        assert not can_transition(TaskStatus.COMPLETED, illegal), illegal


def test_never_silently_abandon_queued_task():
    """A queued task must eventually become RUNNING and reach a terminal state."""
    storage = JSONFileBackend(root_dir="/tmp/exec_abandon_test")
    try:
        from core.capabilities.registry import CapabilityRegistry
        eng = ExecutiveRuntime(storage=storage, capability_registry=CapabilityRegistry(storage=storage))
        from core.executive.models import TaskStep
        t = eng.start_task(
            "not really a capability goal", "tester",
            original_request="not really a capability goal",
            steps=[TaskStep(action="verify_goal", description="Complete goal", params={"request": "not really a capability goal"}).to_dict()],
        )
        assert t.status == TaskStatus.QUEUED
        assert t.status.value in ("queued", "running", "blocked", "completed", "failed", "cancelled")
        assert t.steps, "task must have a plan"
        eng.shutdown()
    finally:
        shutil.rmtree("/tmp/exec_abandon_test", ignore_errors=True)


# ── 2. Persistence & interruption recovery ───────────────────────────────

def test_task_persists_across_engine_restart(storage, registry, fresh_cap):
    eng1 = ExecutiveRuntime(storage=storage, capability_registry=registry)
    t = eng1.start_task(
        f"create a {fresh_cap} capability and install it",
        "tester", original_request=f"create a {fresh_cap} capability and install it",
    )
    eng1.process_ready("tester")  # run exactly one step, then "crash"
    t1 = eng1.get_task("tester", t.task_id)
    assert t1.status == TaskStatus.RUNNING
    assert len(t1.evidence) >= 1

    # brand-new engine over the same storage == interrupted process resumed
    eng2 = ExecutiveRuntime(storage=storage, capability_registry=registry)
    recovered = eng2.recover("tester")
    assert any(r.task_id == t.task_id for r in recovered)
    final = _run_until_terminal(eng2, "tester", t.task_id)
    assert final.status == TaskStatus.COMPLETED
    assert final.progress == 1.0
    assert final.evidence, "completion must carry evidence"
    eng1.shutdown()
    eng2.shutdown()


def test_recovery_repairs_inflight_steps(storage, registry):
    from core.executive.models import Task, TaskStep
    eng = ExecutiveRuntime(storage=storage, capability_registry=registry)
    t = eng.start_task("create a zzz_recover_test capability", "tester")
    # simulate a crash mid-step: task RUNNING with first step stuck RUNNING
    t = eng.get_task("tester", t.task_id)
    t.status = TaskStatus.RUNNING
    t.steps[0].status = TaskStepStatus.RUNNING
    eng.store.save(t)
    eng.shutdown()

    eng2 = ExecutiveRuntime(storage=storage, capability_registry=registry)
    recovered = eng2.recover("tester")
    assert recovered, "recovery must find the active task"
    first = recovered[0]
    assert all(s.status in (TaskStepStatus.PENDING, TaskStepStatus.COMPLETED, TaskStepStatus.SKIPPED) for s in first.steps), \
        "no step may be stuck RUNNING after recovery"


def test_recovery_blocks_unknown_side_effect_instead_of_replaying(storage, registry):
    from core.executive.models import ReplayPolicy, TaskStep

    eng = ExecutiveRuntime(storage=storage, capability_registry=registry)
    task = eng.start_task(
        "append an audit record",
        "tester",
        steps=[TaskStep(action="append_file", description="Append record")],
    )
    task.status = TaskStatus.RUNNING
    step = task.steps[0]
    assert step.replay_policy == ReplayPolicy.BLOCK
    step.status = TaskStepStatus.RUNNING
    step.execution_attempts.append({"attempt_id": "attempt-1", "status": "running"})
    eng.store.save(task)
    eng.shutdown()

    eng2 = ExecutiveRuntime(storage=storage, capability_registry=registry)
    recovered = eng2.recover("tester")
    recovered_task = next(t for t in recovered if t.task_id == task.task_id)
    recovered_step = recovered_task.steps[0]
    assert recovered_task.status == TaskStatus.BLOCKED
    assert recovered_step.status == TaskStepStatus.BLOCKED
    assert recovered_step.execution_attempts[-1]["status"] == "outcome_unknown"
    assert any(e.label == "manual_reconciliation_required" for e in recovered_task.evidence)
    assert eng2.process_ready("tester")["advanced"] == 0

    reconciled = eng2.resolve_interrupted_step(
        "tester",
        task.task_id,
        resolution="completed",
        result={"verified": True},
        detail="Audit record exists exactly once",
    )
    assert reconciled.steps[0].status == TaskStepStatus.COMPLETED
    eng2.process_ready("tester")
    assert eng2.get_task("tester", task.task_id).status == TaskStatus.COMPLETED
    eng2.shutdown()


def test_recovery_requeues_declared_replay_safe_step(storage, registry):
    from core.executive.models import ReplayPolicy, TaskStep

    eng = ExecutiveRuntime(storage=storage, capability_registry=registry)
    task = eng.start_task(
        "inspect registry",
        "tester",
        steps=[TaskStep(action="registry_search", description="Search", params={"capability": "missing"})],
    )
    task.status = TaskStatus.RUNNING
    step = task.steps[0]
    assert step.replay_policy == ReplayPolicy.RETRY
    step.status = TaskStepStatus.RUNNING
    step.execution_attempts.append({"attempt_id": "attempt-2", "status": "running"})
    eng.store.save(task)

    recovered = eng.recover("tester")[0]
    assert recovered.status == TaskStatus.RUNNING
    assert recovered.steps[0].status == TaskStepStatus.PENDING
    assert recovered.steps[0].execution_attempts[-1]["status"] == "interrupted"


def test_active_and_current_task_reporting(storage, registry, fresh_cap):
    eng = ExecutiveRuntime(storage=storage, capability_registry=registry)
    a = eng.start_task(f"create a {fresh_cap} capability", "tester", priority=1)
    eng.process_ready("tester")
    assert eng.current_task("tester").task_id == a.task_id
    assert len(eng.active_tasks("tester")) == 1
    status = eng.task_status("tester", a.task_id)
    assert status["task_id"] == a.task_id
    assert "progress_percent" in status and "current_step" in status
    assert 0 <= status["progress_percent"] <= 100
    eng.shutdown()


# ── 3. Generic acquisition end-to-end ────────────────────────────────────

def test_full_acquisition_flow_with_evidence(engine, fresh_cap):
    t = engine.start_task(
        f"create a {fresh_cap} capability and install it",
        "tester", original_request=f"create a {fresh_cap} capability and install it",
    )
    actions = [s.action for s in t.steps]
    assert actions == ["registry_search", "generate", "validate", "publish", "install", "verify", "verify_goal"]

    final = _run_until_terminal(engine, "tester", t.task_id)
    assert final.status == TaskStatus.COMPLETED, final.error

    completed = [s.action for s in final.completed_steps]
    assert "generate" in completed and "install" in completed and "verify" in completed

    labels = {e.label for e in final.evidence}
    for expected in ("file_generated", "syntax_valid", "registry_published", "installed", "source_file_exists", "module_imports", "registered", "skill_exposed", "skill_callable"):
        assert expected in labels, f"missing evidence label {expected}"


def test_marketplace_found_skips_generation(engine):
    t = engine.start_task(
        "create a command_exec capability and install it",
        "tester", original_request="create a command_exec capability and install it",
    )
    final = _run_until_terminal(engine, "tester", t.task_id)
    assert final.status in (TaskStatus.COMPLETED, TaskStatus.FAILED)
    statuses = {s.action: s.status for s in final.steps}
    assert statuses["registry_search"] == TaskStepStatus.COMPLETED
    assert statuses["generate"] == TaskStepStatus.SKIPPED
    assert statuses["validate"] == TaskStepStatus.SKIPPED
    assert statuses["publish"] == TaskStepStatus.SKIPPED


def test_loose_capability_name_resolves_canonical_id(engine):
    """'command' in the goal must install the marketplace canonical id."""
    t = engine.start_task(
        "create a command execution capability and install it",
        "tester", original_request="create a command execution capability and install it",
    )
    final = _run_until_terminal(engine, "tester", t.task_id)
    assert final.status == TaskStatus.COMPLETED, final.error
    install_evidence = [e for e in final.evidence if e.label == "installed" and e.success]
    assert install_evidence, "expected successful install evidence"
    assert any("command_exec" in (e.detail or "") for e in install_evidence)


def test_verify_calls_first_skill_not_assumed_info(engine):
    """Verification must call the capability's real first skill, not .info."""
    t = engine.start_task(
        "create a command_exec capability and install it",
        "tester", original_request="create a command_exec capability and install it",
    )
    final = _run_until_terminal(engine, "tester", t.task_id)
    assert final.status == TaskStatus.COMPLETED, final.error
    skill_calls = [e for e in final.evidence if e.label == "skill_callable"]
    assert skill_calls and all(e.success for e in skill_calls)


def test_generic_plan_no_hardcoded_capability_names(engine, fresh_cap):
    """The plan for an unknown capability must not know the capability."""
    plan = engine.start_task(
        f"create a {fresh_cap} capability and install it",
        "tester", original_request="x",
    ).steps
    plan_dict = [s.to_dict() for s in plan]
    import json as _json
    blob = _json.dumps(plan_dict)
    assert f'"{fresh_cap}"' in blob or fresh_cap in blob  # appears only as data
    for hardcoded in ("speech", "browser", "docker", "ocr", "command_exec"):
        if hardcoded != fresh_cap:
            assert hardcoded not in blob, f"plan hardcodes {hardcoded}"


# ── 4. Queue ordering & scheduler ────────────────────────────────────────

def test_priority_queue_ordering(storage, registry, fresh_cap):
    eng = ExecutiveRuntime(storage=storage, capability_registry=registry)
    low = eng.start_task(f"create a {fresh_cap}_a capability", "tester", priority=1)
    high = eng.start_task(f"create a {fresh_cap}_b capability", "tester", priority=5)
    assert eng.current_task("tester").task_id == high.task_id
    assert len(eng.active_tasks("tester")) == 2
    eng.shutdown()


def test_scheduler_runs_tasks_in_background(storage, registry, fresh_cap):
    eng = ExecutiveRuntime(storage=storage, capability_registry=registry, autostart=True)
    t = eng.start_task(
        f"create a {fresh_cap} capability and install it",
        "tester", original_request=f"create a {fresh_cap} capability and install it",
    )
    assert eng.scheduler._thread is not None
    deadline = time.time() + 20
    final = None
    while time.time() < deadline:
        final = eng.get_task("tester", t.task_id)
        if final.status.value in ("completed", "failed", "cancelled"):
            break
        time.sleep(0.2)
    assert final is not None and final.status.value in ("completed", "failed", "cancelled")
    eng.shutdown()


# ── 5. Failure, retry, resume, cancel ────────────────────────────────────

def test_fail_then_force_resume(engine):
    t = engine.start_task("create a zzz_fail_resume capability", "tester", priority=1)
    engine.process_ready("tester")
    t = engine.fail_task("tester", t.task_id, "simulated failure")
    assert t.status == TaskStatus.FAILED

    with pytest.raises(IllegalTransition):
        engine.resume_task("tester", t.task_id)  # no force

    t = engine.resume_task("tester", t.task_id, force=True)
    assert t.status == TaskStatus.RUNNING


def test_cannot_cancel_or_fail_terminal_task(engine):
    t = engine.start_task("create a zzz_terminal_check capability", "tester", priority=1)
    engine.process_ready("tester")
    engine.complete_task("tester", t.task_id, result={"outcome": "manual"})
    with pytest.raises(IllegalTransition):
        engine.fail_task("tester", t.task_id, "nope")
    with pytest.raises(IllegalTransition):
        engine.cancel_task("tester", t.task_id)


def test_pause_blocks_only_running(engine):
    t = engine.start_task("create a zzz_pause capability", "tester", priority=1)
    engine.process_ready("tester")
    t = engine.pause_task("tester", t.task_id)
    assert t.status == TaskStatus.BLOCKED
    t = engine.unblock_task("tester", t.task_id)
    assert t.status == TaskStatus.RUNNING


def test_unknown_action_produces_failed_evidence():
    from core.executive.executor import ExecutionContext, execute_step
    from core.executive.models import Task, TaskStep
    ctx = ExecutionContext(identity_id="i", capability_registry=None, storage=None)
    task = Task(task_id="t", goal="g", identity_id="i")
    step = TaskStep(action="no_such_action", description="d")
    ok, result, evidence = execute_step(task, step, ctx)
    assert not ok
    assert any(e.label == "unknown_action" for e in evidence)


# ── 6. Truthful reporting / no hallucination ─────────────────────────────

def test_task_status_reflects_persisted_state(engine, fresh_cap):
    t = engine.start_task(f"create a {fresh_cap} capability and install it", "tester")
    engine.process_ready("tester")
    t = engine.get_task("tester", t.task_id)
    status = engine.task_status("tester", t.task_id)
    assert status["current_step"] == t.current_step
    assert status["progress_percent"] == round(t.progress * 100, 1)
    assert "remaining_steps" in status and "completed_steps" in status
    assert len(status["completed_steps"]) == len(t.completed_steps)


def test_missing_task_reported_truthfully(engine):
    status = engine.task_status("tester", "does-not-exist")
    assert status["found"] is False


def test_checkpoint_persists_progress(engine, fresh_cap):
    t = engine.start_task(f"create a {fresh_cap} capability and install it", "tester")
    engine.process_ready("tester")
    t = engine.checkpoint("tester", t.task_id)
    assert t.checkpoint, "checkpoint must be populated"
    assert "progress" in t.checkpoint


# ── 7. Executive capability API ──────────────────────────────────────────

def test_executive_capability_registered_and_skills():
    from core.capabilities.executive import ExecutiveCapability
    cap = ExecutiveCapability()
    skill_names = {s.name for s in cap.skills()}
    for expected in ("executive.start_task", "executive.resume_task", "executive.pause_task",
                     "executive.current_task", "executive.active_tasks", "executive.task_status",
                     "executive.task_progress", "executive.checkpoint", "executive.recover",
                     "executive.resolve_interrupted_step"):
        assert expected in skill_names


def test_executive_capability_call_start_and_status(storage, registry, fresh_cap):
    from core.capabilities.executive import ExecutiveCapability
    cap = ExecutiveCapability()
    cap._storage = storage
    # ensure engine registered
    eng = get_executive_for(storage)
    if eng is None:
        eng = ExecutiveRuntime(storage=storage, capability_registry=registry)
        register_executive(eng)

    res = cap.call("executive.start_task",
                   goal=f"create a {fresh_cap} capability and install it",
                   identity_id="tester")
    assert res.success
    task_id = res.data["task_id"]

    res = cap.call("executive.task_status", task_id=task_id, identity_id="tester")
    assert res.success
    assert res.data["task_id"] == task_id

    res = cap.call("executive.active_tasks", identity_id="tester")
    assert res.success and res.data["count"] >= 1

    res = cap.call("executive.current_task", identity_id="tester")
    assert res.success and res.data["current_task"] is not None

    eng.shutdown()


def test_executive_capability_recover(storage, registry, fresh_cap):
    from core.capabilities.executive import ExecutiveCapability
    eng = ExecutiveRuntime(storage=storage, capability_registry=registry)
    register_executive(eng)
    t = eng.start_task(f"create a {fresh_cap} capability and install it", "tester")
    eng.process_ready("tester")
    eng.shutdown()

    cap = ExecutiveCapability()
    cap._storage = storage
    res = cap.call("executive.recover", identity_id="tester")
    assert res.success
    assert any(x == t.task_id for x in res.data["recovered"])


# ── 8. Workflow helpers ──────────────────────────────────────────────────

def test_extract_capability_name_variants():
    assert extract_capability_name("create a speech capability") == "speech"
    assert extract_capability_name("build a browser skill") == "browser"
    assert extract_capability_name("make an ocr capability") == "ocr"
    assert extract_capability_name("install docker capability") == "docker"
    assert extract_capability_name("what is the weather") is None


def test_is_acquisition_goal():
    assert is_acquisition_goal("create a speech capability")
    assert is_acquisition_goal("Please build a new command_exec capability")
    assert not is_acquisition_goal("what time is it")
    assert not is_acquisition_goal("how many stars does lacebx/IdentityOS have")


def test_status_questions_are_not_acquisition_goals():
    from core.prometheus.pipeline import _is_status_question
    for q in [
        "did you finish creating the speech capability?",
        "what are you working on?",
        "is the command_exec task done",
        "are you still building weather",
        "can you check the status of my speech task",
    ]:
        assert _is_status_question(q), q
        assert not is_acquisition_goal(q), q
    for cmd in [
        "create a speech capability and install it",
        "build me a weather skill",
        "please add a text capability to my identity",
        "install docker capability",
    ]:
        assert not _is_status_question(cmd), cmd
        assert is_acquisition_goal(cmd), cmd


def test_delegate_to_executive_skips_status_questions_and_duplicates(tmp_path):
    """Prometheus delegation must not re-commit on questions, and must not
    re-queue a capability that already completed."""
    from core.executive.workflow import build_acquisition_plan
    from core.prometheus.models import CapabilityNeed, EvolutionResult
    from core.prometheus.pipeline import EvolutionPipeline
    from runtime.persistence import JSONFileBackend

    class FakeRuntime:
        def __init__(self, root):
            self.executive = ExecutiveRuntime(storage=JSONFileBackend(root_dir=root))

    rt = FakeRuntime(str(tmp_path))
    rt.executive.scheduler.start = lambda: None  # don't race the test
    pipeline = EvolutionPipeline()
    storage = JSONFileBackend(root_dir=str(tmp_path))

    def make_need(cap, request):
        return CapabilityNeed(
            skill_keywords=[cap],
            confidence=0.9,
            source="user_input",
            original_request=request,
            suggested_capability_ids=[cap],
        )

    # 1) A status question must NOT create a task.
    res = pipeline._delegate_to_executive(
        make_need("speech", "did you finish creating the speech capability?"),
        "tester", rt, storage, None,
    )
    assert res is not None and not res.acquired
    assert rt.executive.active_tasks("tester") == []

    # 2) A real acquisition creates a task.
    res = pipeline._delegate_to_executive(
        make_need("exec_test_q", "create a exec_test_q capability and install it"),
        "tester", rt, storage, None,
    )
    assert res is not None
    assert len(rt.executive.active_tasks("tester")) == 1

    # 3) Re-delegating the same capability is idempotent (active task exists).
    res = pipeline._delegate_to_executive(
        make_need("exec_test_q", "create a exec_test_q capability and install it"),
        "tester", rt, storage, None,
    )
    assert not res.acquired and "already active" in (res.acquisition_record.error or "")

    # 4) A completed capability must not be re-queued.  Finish the step-2
    #    task (running -> completed) so only the terminal check applies.
    from core.executive.models import TaskStatus
    from core.executive.state import can_transition, transition as _transition
    _active = rt.executive.active_tasks("tester")[0]
    if can_transition(_active.status, TaskStatus.RUNNING):
        _transition(_active, TaskStatus.RUNNING)
        rt.executive.store.save(_active)
    rt.executive.complete_task("tester", _active.task_id)
    task = rt.executive.start_task(
        identity_id="tester",
        goal="create a exec_test_q capability",
        capability_id="exec_test_q",
        steps=build_acquisition_plan("exec_test_q"),
    )
    _transition(task, TaskStatus.RUNNING)
    rt.executive.store.save(task)
    rt.executive.complete_task("tester", task.task_id)
    res = pipeline._delegate_to_executive(
        make_need("exec_test_q", "create a exec_test_q capability and install it"),
        "tester", rt, storage, None,
    )
    assert not res.acquired and "already completed" in (res.acquisition_record.error or "")


def test_registry_reload_binds_storage(tmp_path):
    """Capabilities re-loaded from storage must have storage re-bound so skill
    calls reach the live engine (fixes 'NoneType' object has no attribute
    'load' when the LLM calls executive.current_task in a fresh process)."""
    from core.capabilities.registry import CapabilityRegistry
    storage = JSONFileBackend(root_dir=str(tmp_path))
    reg = CapabilityRegistry(storage)
    reg.install("tester", "executive")

    # Simulate a fresh process: new registry over the same storage.
    reg2 = CapabilityRegistry(storage)
    cap = reg2.get("tester", "executive")
    assert cap is not None
    assert cap._storage is not None, "install() must re-bind storage on reload"

    r = cap.call("executive.history", identity_id="tester")
    assert r.success, r.error
